# Docker Compose конфигурация для использования образов из GitHub Container Registry
# Использует pre-built образы вместо локальной сборки
# Для локальной сборки используйте docker-compose.yml

services:
  # Telegram Bot
  bot:
    image: ghcr.io/natapage/telegram-bot-bot:latest
    container_name: telegram-bot
    env_file:
      - .env
    volumes:
      - ./prompts:/app/prompts:ro
      - ./telegram_bot.db:/app/telegram_bot.db
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - api

  # FastAPI Backend
  api:
    image: ghcr.io/natapage/telegram-bot-api:latest
    container_name: telegram-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./prompts:/app/prompts:ro
      - ./telegram_bot.db:/app/telegram_bot.db
      - ./logs:/app/logs
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    image: ghcr.io/natapage/telegram-bot-frontend:latest
    container_name: telegram-frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped
    depends_on:
      - api
