services:
  # Telegram Bot
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram-bot
    env_file:
      - .env
    volumes:
      - ./prompts:/app/prompts:ro
      - ./telegram_bot.db:/app/telegram_bot.db
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - api

  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: telegram-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./prompts:/app/prompts:ro
      - ./telegram_bot.db:/app/telegram_bot.db
      - ./logs:/app/logs
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: telegram-frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped
    depends_on:
      - api
